// src/config/worlds.config.js
// 10 Topic-themed worlds for RuleQuest (Grade 7 Term-to-Term Rules)

export const WORLDS = [
  {
    id: 0,
    name: "Reading the Blueprint",
    emoji: "📋",
    accent: "var(--world-0)",
    description: "State a single-operation term-to-term rule in words",
    conceptFocus: "state-single-step-rule",
    boss: { name: "The Silent Blueprint", emoji: "📋", reward: "Apprentice Badge" },
  },
  {
    id: 1,
    name: "Testing the Machine",
    emoji: "🔧",
    accent: "var(--world-1)",
    description: "Verify a proposed rule against every consecutive pair",
    conceptFocus: "verify-rule-every-pair",
    boss: { name: "The Faulty Tester", emoji: "🔧", reward: "Inspector's Badge" },
  },
  {
    id: 2,
    name: "Running the Machine Forward",
    emoji: "⚙️",
    accent: "var(--world-2)",
    description: "Apply a single-operation rule to generate terms",
    conceptFocus: "apply-single-step-rule",
    boss: { name: "The Runaway Gear", emoji: "⚙️", reward: "Operator's Badge" },
  },
  {
    id: 3,
    name: "The Two-Gear Machine",
    emoji: "⚙️",
    accent: "var(--world-3)",
    description: "Apply a compound (two-step) rule to generate terms",
    conceptFocus: "apply-compound-rule",
    boss: { name: "The Jammed Two-Gear", emoji: "⚙️", reward: "Mechanic's Badge" },
  },
  {
    id: 4,
    name: "Reverse Engineering",
    emoji: "↩️",
    accent: "var(--world-4)",
    description: "Work backwards through a single-step rule",
    conceptFocus: "work-backwards-single-step",
    boss: { name: "The Backwards Bandit", emoji: "↩️", reward: "Reverse Badge" },
  },
  {
    id: 5,
    name: "Full Reverse",
    emoji: "🔄",
    accent: "var(--world-5)",
    description: "Work backwards through a compound rule",
    conceptFocus: "work-backwards-compound-rule",
    boss: { name: "The Double-Reverse Rogue", emoji: "🔄", reward: "Master Reverser Badge" },
  },
  {
    id: 6,
    name: "Sort the Machines",
    emoji: "🏷️",
    accent: "var(--world-6)",
    description: "Classify a rule as arithmetic, geometric, or neither",
    conceptFocus: "classify-rule-type",
    boss: { name: "The Mislabeled Machine", emoji: "🏷️", reward: "Classifier Badge" },
  },
  {
    id: 7,
    name: "The Twin-Input Machine",
    emoji: "🔀",
    accent: "var(--world-7)",
    description: "Recognise and continue a Fibonacci-type sequence",
    conceptFocus: "fibonacci-type-sequences",
    boss: { name: "The Twin-Input Trickster", emoji: "🔀", reward: "Fibonacci Badge" },
  },
  {
    id: 8,
    name: "The Inventor's Challenge",
    emoji: "🏗️",
    accent: "var(--world-8)",
    description: "Full applied multi-step real-world scenario",
    conceptFocus: "applied-multi-step-rule",
    boss: { name: "The Grand Contraption", emoji: "🏗️", reward: "Inventor's Badge" },
  },
  {
    id: 9,
    name: "The Grand Workshop Showcase",
    emoji: "🎩",
    accent: "var(--world-9)",
    description: "Mixed review of every concept above; hardest boss",
    conceptFocus: "mixed-review",
    boss: { name: "The Master Inventor", emoji: "🎩", reward: "Chief Engineer Trophy" },
  },
];

export const PLAY_MODES = [
  {
    id: 'guided',
    name: 'Guided Practice',
    icon: '🧭',
    desc: '5 questions with hints, no time pressure',
    questionCount: 5,
    hints: true,
    timed: false,
    lives: false,
  },
  {
    id: 'independent',
    name: 'Independent Practice',
    icon: '✍️',
    desc: '10 questions, no hints, full XP',
    questionCount: 10,
    hints: false,
    timed: false,
    lives: false,
  },
  {
    id: 'timed',
    name: 'Timed Challenge',
    icon: '⏱️',
    desc: '8 questions in 60 seconds, bonus XP',
    questionCount: 8,
    hints: false,
    timed: true,
    timeLimit: 60,
    lives: false,
  },
  {
    id: 'boss',
    name: 'Boss Battle',
    icon: '👑',
    desc: '5 questions, 3 lives — defeat the boss!',
    questionCount: 5,
    hints: false,
    timed: false,
    lives: true,
  },
];

export const XP_REWARDS = {
  CORRECT: 10,
  STREAK_BONUS: 15,
  STATION_COMPLETE: 20,
  WORLD_COMPLETE: 50,
  BOSS_WIN: 100,
};
